mysql:
  host: localhost
  port: 3306
  username: root
  password: 123456
  dbname: umeet
  charset: utf8mb4

redis:
  addr: localhost:6379
  password: ""
  # db: 0

router:
  # addr: 0.0.0.0:8080 #any wifi
  # addr: 192.168.2.116:8080 #home wifi
  addr: 127.0.0.1:8080

